config/routes.rb
ReservationProject::Application.routes.draw do
  
  get "welcome/index"

  Rails.application.routes.draw do
  devise_for :users
    
    resources :reservations do
        resources :reviews
    end
    root 'welcome#index'
    end 

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.nil?
      can :read, Reservation
    else
      can [:read, :create], Reservation
      can [:update, :destroy], Reservation, user_id: user.id
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
	has_many :reviews
	accepts_nested_attributes_for :reviews
	validates :pickup_location, presence:true,
								length: {maximum: 19 }
	validates :pickup_time, presence:true
	validates :dropoff_time, presence:true
                    
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :reservation
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   has_many :reservations
   has_many :reviews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
         validates :email, presence: true, length: { maximum: 255 },
 format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reservation_item_controller.rb
class ReservationItemController < ApplicationController
	def new
		
	end
	def create
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	
  def index
    @reservations = Reservation.all
  end
	
  def show
  	@reservation = Reservation.find(params[:id])
	end
	
  def new
		@reservation=Reservation.new
	end
	
  def edit
    @reservation = Reservation.find(params[:id])
	end
	
  def create
		
    @reservation = Reservation.new(reservation_params)
    @reservation.user=current_user
    if @reservation.save
      redirect_to @reservation
    else
      render 'new'
    end
  end
 
  def update
    @reservation = Reservation.find(params[:id])
   if @reservation.user == current_user
      if @reservation.update(reservation_params)
        redirect_to reservations_path
      else
        render 'edit'
      end
    else 
      redirect_to reservations_path
      flash[:notice] = "Not ur post. Can't Edit"
    end
  end 

  def destroy
     @reservation = Reservation.find(params[:id])
    if @reservation.user==current_user
    	@reservation.destroy
    	redirect_to reservations_path
    else
    	redirect_to reservations_path
      flash[:notice] = "Not ur post. Can't Delete"
    end
  end	

	private 

	def reservation_params
	 params.require(:reservation).permit(:pickup_location,:pickup_time,:dropoff_time)
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
def index
     @reservation = Reservation.find(params[:reservation_id])
    #2nd you get all the comments of this post
    @reviews = @reservation.reviews
end

def create
	@reservation = Reservation.find(params[:reservation_id])
	@review = @reservation.reviews.create(review_params)
	@review.user=current_user
	@review.save
	redirect_to reservation_reviews_path
end

def new
		reservation = Reservation.find(params[:reservation_id])
    #2nd you build a new one
    @review = reservation.reviews.build
end

def show
	@review = Review.find(params[:id])
end

def edit
	reservation = Reservation.find(params[:reservation_id])
    @review = reservation.reviews.find(params[:id])
end

def update
    @reservation = Reservation.find(params[:reservation_id])
    @review = @reservation.reviews.find(params[:id])
    if @review.user == current_user
    	if @review.update(review_params)
        	redirect_to reservation_reviews_path
      	else
        render 'edit'
      	end
    else 
      redirect_to reservation_reviews_path
      flash[:notice] = "Not ur Review. Can't Edit"
    end 
end 

def destroy
	@reservation=Reservation.find(params[:reservation_id])
     @review = @reservation.reviews.find(params[:id])
     if @review.user==current_user
    	@review.destroy
    	redirect_to reservation_reviews_path
    else
    	redirect_to reservation_reviews_path
      	flash[:notice] = "Not ur Review. Can't Delete"
    end
end	


private

def review_params
	params.require(:review).permit(:reviewer, :review)
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservation_item_helper.rb
module ReservationItemHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReservationProject</title>
   <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background: #A1234G">
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
    </div>
<% end %>

<%if current_user%>
	<%=current_user.email %> <%= link_to 'Logout', destroy_user_session_path, method: :delete,:class => 'btn btn-primary' %>
<%else %>
	<%= link_to 'Login', new_user_session_path, :class => 'btn btn-primary' %>
<%end%>

<%= yield %>

</body>
</html>

app/views/reservation_item/new.html.erb
<h1> New Reservation </h1>
<%= form_for :reservation_item do |f| %>
  <p>
    <%= f.label :Pickup_location %><br>
    <%= f.text_field :pickup_location %>
  </p>
 
  <p>
    <%= f.label :Pickup_Time %><br>
    <%= f.datetime_select :pickup_time %>
  </p>
  <p>
    <%= f.label :Dropoff_Time %><br>
    <%= f.datetime_select :dropoff_time %>
  </p> 
  <p>
    <%= f.submit %>
  </p>
  
<% end %>

app/views/reservations/_form.html.erb
<%= form_for @reservation do |f| %>
<% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@reservation.errors.count, "error") %> prohibited
        this reservation from being saved:
      </h2>
      <ul>
        <% @reservation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
  <p>
    <%= f.label :Pickup_location %><br>
    <%= f.text_field :pickup_location %>
  </p>
 
  <p>
    <%= f.label :Pickup_Time %><br>
    <%= f.datetime_select :pickup_time %>
  </p>
  <p>
    <%= f.label :Dropoff_Time %><br>
    <%= f.datetime_select :dropoff_time %>
  </p> 
  <p>
    <%= f.submit 'Save Reservation', class: 'btn btn-primary' %>
  </p>
  
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>
 <%= render 'form', post: @reservation %>
<%= link_to 'Back', reservations_path, :class => 'btn btn-default' %>
<td><%= link_to 'Destroy', @reservation,
              method: :delete,
              data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
</td>

app/views/reservations/index.html.erb
<h1>Listing Reservations</h1>
 
<table>
  <tr>
    <th>Location</th>
    <th>Pickup Time</th>
    <th>Dropoff Time</th>
    <th colspan="2"></th>
  </tr>
 
  <% @reservations.each do |reservation| %>
    <tr>
      <td><%= reservation.pickup_location %></td>
      <td><%= reservation.pickup_time %></td>
      <td><%= reservation.dropoff_time %></td>
      
      <td><%= link_to 'Show', reservation_path(reservation), :class => 'btn btn-default' %></td>
      
      <td><%= link_to 'Edit', edit_reservation_path(reservation), :class => 'btn btn-default' %></td>
      
      <td><%= link_to 'Destroy', reservation_path(reservation),
              method: :delete,
              data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'New Reservation', new_reservation_path, :class => 'btn btn-default' %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>
<%= render 'form', post: @reservation %> 
<%= link_to 'Back', reservations_path, :class => 'btn btn-default' %>

app/views/reservations/show.html.erb
<p>
	<strong>Pickup Location</strong>
	<%= if @reservation!=nil
		@reservation.pickup_location
		end %>
</p>
<p>
	<strong>Pickup Time</strong>
	<%= if @reservation!=nil
		@reservation.pickup_time
		end %>
</p>
<p>
	<strong>Dropoff Time</strong>
	<%= if @reservation!=nil
		@reservation.dropoff_time
		end %>
</p>
<%= link_to 'Reviews', reservation_reviews_path(@reservation) %>
<%= link_to 'Back', reservations_path, :class => 'btn btn-default' %>
<%= link_to 'Edit', edit_reservation_path(@reservation), :class => 'btn btn-default' %>

app/views/reviews/_form.html.erb
<%= form_for([@review.reservation, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Reviewer %><br />
    <%= f.text_field :reviewer %>
  </div>
  <div class="field">
    <%= f.label :review %><br />
    <%= f.text_area :review %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Reviews</h1>

<%= render 'form', post: @review %>


<%= link_to 'Show', [@review.reservation, @review] %> |
<!-- /posts/:post_id/comments/ -->
<%= link_to 'Back', reservation_reviews_path(@review.reservation) %>

app/views/reviews/index.html.erb
<h1>Listing Reviews</h1>

<table>
  <tr>
    <th>Reviewer</th>
    <th>Review</th>
    <th>Reservation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |r| %>
  <tr>
    <td><%= r.reviewer %></td>
    <td><%= r.review %></td>

    <td><%= link_to 'Show', [r.reservation, r] %></td>
    
    <td><%= link_to 'Edit', edit_reservation_review_path(r.reservation, r)%></td>
    <td><%= link_to 'Destroy', [r.reservation, r], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'New Review', new_reservation_review_path %> 
<%= link_to 'Back', reservation_path(@review) %>  

app/views/reviews/new.html.erb
<h1>New Review</h1>
<%= render 'form', post: @review%>
<%= link_to 'Back', reservation_reviews_path(@review.reservation)%>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Reviewer:</b>
  <%= @review.reviewer %>
</p>

<p>
  <b>Review:</b>
  <%= @review.review %>
</p>

<%= link_to 'Edit', edit_reservation_review_path(@review.reservation, @review) %> 

<%= link_to 'Back', reservation_reviews_path(@review.reservation) %>

app/views/welcome/index.html.erb
<h1>Reservation Portal</h1>
<%= link_to 'Reservation Portal', controller: 'reservations' %>